forge "https://forgeapi.puppetlabs.com"

# Dependencies for this module
mod 'puppetlabs/stdlib'
mod 'example42/puppi'

# Module for installing packages from apt
mod 'puppetlabs-apt', "< 2.0.0"

mod 'nsidc/nsidc_miniconda',
  :git => 'git@bitbucket.org:/nsidc/puppet-nsidc-miniconda.git'

# Module for creating NSIDC Jenkins servers
mod 'nsidc/nsidc_jenkins',
  :git => 'git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git',
  :ref => 'latest'
