forge "https://forgeapi.puppetlabs.com"

# Dependencies for this module
mod 'puppetlabs/stdlib'
mod 'example42/puppi'

# Module for creating NSIDC Jenkins servers
mod 'nsidc/nsidc_jenkins',
  :git => 'git@bitbucket.org:/nsidc/puppet-nsidc-jenkins.git',
  :ref => 'latest'
